ubuntu@mtk-genio:~/Desktop/test$ python3 label_image.py --label_file labels_mobilenet_quant_v1_224.txt --image grace_hopper.jpg --model_file mobilenet_v1_1.0_224_quant.tflite -e /usr/lib/gpu_external_delegate.so
Loading external delegate from /usr/lib/gpu_external_delegate.so with args: {}
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/label_image.py", line 69, in <module>
    tflite.load_delegate(args.ext_delegate, ext_delegate_options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 166, in load_delegate
    delegate = Delegate(library, options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 73, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/gpu_external_delegate.so: cannot open shared object file: No such file or directory
Exception ignored in: <function Delegate.__del__ at 0xffff7ad1f400>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 109, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

ubuntu@mtk-genio:/usr/lib$ find / -name gpu_external_delegate.so 2>dev/null
bash: dev/null: No such file or directory

ubuntu@mtk-genio:/$ find / -name gpu_external_delegate.so 2>/dev/null
ubuntu@mtk-genio:/$ 

ubuntu@mtk-genio:/usr/lib$ sudo apt-get install libvulkan1 vulkan-utils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package vulkan-utils

