ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ sudo python3 test.py --auto
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/benchmark_dla/test.py", line 194, in <module>
    benchmark_tflite_model(file, args.target, args.count, compile_options, cache_dla, args.profile)
  File "/home/ubuntu/Desktop/test/benchmark_dla/test.py", line 99, in benchmark_tflite_model
    gen_input_bin(modeil_io, input_bin)
NameError: name 'gen_input_bin' is not defined. Did you mean: 'input_bin'?

------------------------------------

ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ python3 quantize.py 
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/benchmark_dla/quantize.py", line 7, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 2073, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 900, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1005, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: yolov5x.tflite/{saved_model.pbtxt|saved_model.pb}
