ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ sudo python3 test.py --auto
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/benchmark_dla/test.py", line 194, in <module>
    benchmark_tflite_model(file, args.target, args.count, compile_options, cache_dla, args.profile)
  File "/home/ubuntu/Desktop/test/benchmark_dla/test.py", line 99, in benchmark_tflite_model
    gen_input_bin(modeil_io, input_bin)
NameError: name 'gen_input_bin' is not defined. Did you mean: 'input_bin'?

------------------------------------

ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ python3 quantize.py 
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/benchmark_dla/quantize.py", line 7, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 2073, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 900, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1005, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: yolov5x.tflite/{saved_model.pbtxt|saved_model.pb}

-----------------------------------

ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ python3 quantize.py 
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/benchmark_dla/quantize.py", line 4, in <module>
    converter = tf.lite.TFLiteConverter.from_tflite_model("yolov5x.tflite")
AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_tflite_model'. Did you mean: 'from_keras_model'?

-----------------------------------------

ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ onnx-tf convert -i yolov5x.onnx -o yolov5x_tf_saved_model
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/onnx-tf", line 5, in <module>
    from onnx_tf.cli import main
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/backend.py", line 29, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/common/handler_helper.py", line 3, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/handlers/backend/hardmax.py", line 3, in <module>
    import tensorflow_addons as tfa
ModuleNotFoundError: No module named 'tensorflow_addons'


---------------------------------------------

ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ pip install tensorflow-addons
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons

----------------------------------------

# Install dependencies if not already installed
sudo apt-get install build-essential cmake

# Clone the tensorflow-addons repository
git clone https://github.com/tensorflow/addons.git

# Navigate into the tensorflow-addons directory
cd addons

# Install using pip
pip install .


OPPURE 


pip install tf2onnx

python -m tf2onnx.convert --opset 13 --input yolov5x.onnx --output yolov5x_tf_saved_model --saved-model

----------------------------------------

ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ onnx-tf convert -i yolov5x.onnx -o yolov5x_tf_saved_model
/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
2024-10-03 10:59:32,691 - onnx-tf - INFO - Start converting onnx pb to tf pb:
2024-10-03 10:59:34,238 - onnx-tf - INFO - Unknown op ConstantFill in domain `ai.onnx`.
2024-10-03 10:59:34,239 - onnx-tf - INFO - Unknown op ImageScaler in domain `ai.onnx`.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/onnx-tf", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/converter.py", line 20, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/converter.py", line 136, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/backend.py", line 66, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/backend.py", line 86, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    output_ops = cls._onnx_node_to_tensorflow_op(onnx_node,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/backend.py", line 252, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/handlers/backend/sigmoid.py", line 18, in version_6
    return [cls.make_tensor_from_onnx_node(node, **kwargs)]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onnx_tf/handlers/backend_handler.py", line 188, in _run_tf_func
    return tf_func(**kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
ValueError: '/model.0/act/Sigmoid' is not a valid root scope name. A root scope name has to match the following pattern: ^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$

----------------------------------

import onnx

# Load the ONNX model
model = onnx.load("yolov5x.onnx")

# Loop through the nodes and fix the names
for node in model.graph.node:
    if node.name.startswith("/"):
        # Fix the name by removing or replacing invalid characters
        node.name = node.name.replace("/", "_")

# Save the modified ONNX model
onnx.save(model, "yolov5x_fixed.onnx")



onnx-tf convert -i yolov5x_fixed.onnx -o yolov5x_tf_saved_model

------------------------------


ubuntu@mtk-genio:~/Desktop/test/benchmark_dla$ python3 -m tf2onnx.convert --opset 13 --input yolov5x.onnx --output yolov5x_tf_saved_model --saved-model
/usr/lib/python3.10/runpy.py:126: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
usage: convert.py [-h] [--input INPUT] [--graphdef GRAPHDEF] [--saved-model SAVED_MODEL] [--tag TAG] [--signature_def SIGNATURE_DEF] [--concrete_function CONCRETE_FUNCTION]
                  [--checkpoint CHECKPOINT] [--keras KERAS] [--tflite TFLITE] [--tfjs TFJS] [--large_model] [--output OUTPUT] [--inputs INPUTS] [--outputs OUTPUTS]
                  [--ignore_default IGNORE_DEFAULT] [--use_default USE_DEFAULT] [--rename-inputs RENAME_INPUTS] [--rename-outputs RENAME_OUTPUTS] [--use-graph-names]
                  [--opset OPSET] [--dequantize] [--custom-ops CUSTOM_OPS] [--extra_opset EXTRA_OPSET] [--load_op_libraries LOAD_OP_LIBRARIES]
                  [--target {rs4,rs5,rs6,caffe2,tensorrt,nhwc}] [--continue_on_error] [--verbose] [--debug] [--output_frozen_graph OUTPUT_FROZEN_GRAPH]
                  [--inputs-as-nchw INPUTS_AS_NCHW] [--outputs-as-nchw OUTPUTS_AS_NCHW]
convert.py: error: argument --saved-model: expected one argument

-----------------------------------

python3 -m tf2onnx.convert --opset 13 --input yolov5x.onnx --output yolov5x_tf_saved_model --saved-model yolov5x_tf_saved_model_dir
